//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamYenMy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoiHoc
    {
        public long MaKhoa { get; set; }
        public string TenKhoa { get; set; }
        public Nullable<int> SoHV { get; set; }
        public Nullable<int> ThuThu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
