//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamYenMy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomNguoiDung_Quyen
    {
        public string MaNhomNguoiDung { get; set; }
        public string MaQuyen { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual NhomNguoiDung NhomNguoiDung { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
