//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamYenMy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDiemDanh
    {
        public long MaDiemDanh { get; set; }
        public Nullable<long> MaLop { get; set; }
        public Nullable<System.DateTime> NgayDiemDanh { get; set; }
        public Nullable<long> MaHV { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
