//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamYenMy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public long MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string MetaTitle { get; set; }
        public string Mota { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDung { get; set; }
        public string NguoiViet { get; set; }
        public string NguoiDang { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<long> MaLoaiTin { get; set; }
        public Nullable<System.DateTime> TopHot { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual LoaiTinTuc LoaiTinTuc { get; set; }
    }
}
